FROM python:3.9-slim

# Установка системных зависимостей
RUN apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копирование requirements 
COPY requirements.txt .

# Установка зависимостей
RUN pip install --no-cache-dir numpy==1.21.2 --only-binary=:all:
RUN pip install --no-cache-dir -r requirements.txt

# Копирование всего проекта
COPY . .

# Команда запуска
CMD ["python", "bot.py"]